// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DepthLimitKind = "checkCrossProductUnion_DepthLimit" | "checkTypeRelatedTo_DepthLimit" | "getTypeAtFlowNode_DepthLimit" | "instantiateType_DepthLimit" | "recursiveTypeRelatedTo_DepthLimit" | "removeSubtypes_DepthLimit" | "traceUnionsOrIntersectionsTooLarge_DepthLimit" | "typeRelatedToDiscriminatedType_DepthLimit";
