// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PackageManager } from "./PackageManager";
import type { TypeScriptCompilerVariant } from "./TypeScriptCompilerVariant";

export type EventGenerateTraceFailData = { duration: bigint, packageManager: PackageManager, stdout: string | null, stderr: string | null, maxOldSpaceSize: number | null, maxStackSize: number | null, tscExtraFlags: string, typescriptCompilerVariant: TypeScriptCompilerVariant, applyTscProjectFlag: boolean, };
