// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppMode } from "./AppMode";
import type { EventAppStartedSuccessData } from "./EventAppStartedSuccessData";

export type EventAppStartedSuccess = { name: "app_started_success", data: EventAppStartedSuccessData, sessionId: string, timestamp: bigint, version: string, platform: string, mode: AppMode, };
