// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppMode } from "./AppMode";
import type { EventGenerateTraceFailData } from "./EventGenerateTraceFailData";

export type EventGenerateTraceFail = { name: "generate_trace_fail", data: EventGenerateTraceFailData, sessionId: string, timestamp: bigint, version: string, platform: string, mode: AppMode, };
