// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppMode } from "./AppMode";
import type { EventTypeGraphSuccessData } from "./EventTypeGraphSuccessData";

export type EventTypeGraphSuccess = { name: "type_graph_success", data: EventTypeGraphSuccessData, sessionId: string, timestamp: number, version: string, platform: string, mode: AppMode, };
