// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppMode } from "./AppMode";
import type { EventAppStartedFailData } from "./EventAppStartedFailData";

export type EventAppStartedFail = { name: "app_started_fail", data: EventAppStartedFailData, sessionId: string, timestamp: number, version: string, platform: string, mode: AppMode, };
