// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppMode } from "./AppMode";
import type { EventTypeGraphFailData } from "./EventTypeGraphFailData";

export type EventTypeGraphFail = { name: "type_graph_fail", data: EventTypeGraphFailData, sessionId: string, timestamp: bigint, version: string, platform: string, mode: AppMode, };
