// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppMode } from "./AppMode";
import type { EventAnalyzeTraceFailData } from "./EventAnalyzeTraceFailData";

export type EventAnalyzeTraceFail = { name: "analyze_trace_fail", data: EventAnalyzeTraceFailData, sessionId: string, timestamp: number, version: string, platform: string, mode: AppMode, };
