// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LinkKind } from "./LinkKind";
import type { StrippedLinkKindData } from "./StrippedLinkKindData";

export type EventTypeGraphSuccessData = { duration: bigint, nodeCount: number, linkCount: number, linkKindDataByKind: { [key in LinkKind]?: StrippedLinkKindData }, };
