// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DepthLimitKind } from "./DepthLimitKind";
import type { FileStatistics } from "./FileStatistics";

export type EventAnalyzeTraceSuccessData = { duration: bigint, totalDuplicatePackages: number, mostDuplicatedPackageInstances: number, totalHotspots: number, depthLimitCounts: { [key in DepthLimitKind]?: number }, fileStatistics: FileStatistics, };
