// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppMode } from "./AppMode";
import type { EventGenerateTraceSuccessData } from "./EventGenerateTraceSuccessData";

export type EventGenerateTraceSuccess = { name: "generate_trace_success", data: EventGenerateTraceSuccessData, sessionId: string, timestamp: bigint, version: string, platform: string, mode: AppMode, };
