// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Settings } from "./Settings";
import type { SourceHistory } from "./SourceHistory";

export type EventAppStartedSuccessData = { settings: Settings, sourceHistory: SourceHistory, };
