// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppMode } from "./AppMode";
import type { EventAnalyzeTraceSuccessData } from "./EventAnalyzeTraceSuccessData";

export type EventAnalyzeTraceSuccess = { name: "analyze_trace_success", data: EventAnalyzeTraceSuccessData, sessionId: string, timestamp: number, version: string, platform: string, mode: AppMode, };
