// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FileStatistics = { totalFiles: number, totalDuration: number, meanDuration: number, maxDuration: number, minDuration: number, };
