// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TypeScriptCompilerVariant } from "./TypeScriptCompilerVariant";

export type Settings = { relativePaths: boolean, preferEditorOpen: boolean, preferredEditor: string | null, extraTscFlags: string, applyTscProjectFlag: boolean, maxOldSpaceSize: number | null, maxStackSize: number | null, typescriptCompilerVariant: TypeScriptCompilerVariant, maxNodes: number, analyticsConsent: Array<string>, };
