// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SourceHistory = { fromEnv: Array<string>, fromFlag: Array<string>, fromFile: Array<string>, fromDefault: Array<string>, };
