// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SourceHistory = { from_env: Array<string>, from_flag: Array<string>, from_file: Array<string>, from_default: Array<string>, };
