// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StrippedDirectionData } from "./StrippedDirectionData";

/**
 * Stats for a specific link kind: ordered list of (target_id, [source_ids])
 * Ordered by number of sources (most connected first)
 */
export type StrippedLinkKindData = { byTarget: StrippedDirectionData, bySource: StrippedDirectionData, linkCount: number, };
